// ============================================================
//  ข้อมูลเว็บไซต์ — แก้ไขที่ไฟล์นี้ที่เดียว
// ============================================================

const CONTACT = {
  phone: { tel: "0989835090", display: "098-983-5090" },
  // ขึ้นบรรทัดใหม่ด้วย \n
  address: "เลขที่ 9/69 หมู่ 1\nซอยบ้านกลาง 1/4 (ซอยเลียบคลองประปา)\nถนนปทุม-รังสิต ตำบลบ้านกลาง\nอำเภอเมือง จังหวัดปทุมธานี 12000",
};
// LINE: ใช้รูป QR Code ที่ images/line-qr.jpg (เปลี่ยนรูปนี้ถ้ามี QR ใหม่)

// ผลงาน (ภาพทั้งหมดอยู่ในโฟลเดอร์ images/)
// category ต้องตรงกับ data-filter ของภาพ 4 ช่องใน index.html
// type: "ผลงานจริง" หรือ "ภาพออกแบบ 3D"
const PROJECTS = [
  { title: "บ้านพักอาศัย ชุมพร — ห้องนั่งเล่น", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image58.jpg" },
  { title: "โรงเรียนอนุบาล — ห้องเรียน", category: "โรงเรียนอนุบาล", type: "ภาพออกแบบ 3D", image: "images/image64.jpg" },
  { title: "Reignwood Park — ห้องนั่งเล่น", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image23.jpg" },
  { title: "ศูนย์การเรียนรู้ — ห้องสมุด", category: "พื้นที่การเรียนรู้", type: "ภาพออกแบบ 3D", image: "images/image92.jpg" },
  { title: "Maiyalap 14 — ห้องนั่งเล่น", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image108.jpg" },
  { title: "อาคารเรียน — ภายนอก", category: "ภายนอกอาคาร", type: "ภาพออกแบบ 3D", image: "images/image112.jpg" },
  { title: "บ้านพักอาศัย ชุมพร — ห้องครัว", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image60.jpg" },
  { title: "โรงเรียนอนุบาล — ลานเล่นในร่ม", category: "โรงเรียนอนุบาล", type: "ภาพออกแบบ 3D", image: "images/image75.jpg" },
  { title: "Reignwood Park — ห้องครัว", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image18.jpg" },
  { title: "บ้านพักอาศัย ชุมพร — โถงบันได", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image55.jpg" },
  { title: "บ้านพักอาศัย ชุมพร — ห้องทานอาหาร", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image56.jpg" },
  { title: "บ้านพักอาศัย ชุมพร — โถงเพดานสูง", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image57.jpg" },
  { title: "บ้านพักอาศัย ชุมพร — ห้องทำงาน", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image59.jpg" },
  { title: "บ้านพักอาศัย ชุมพร — ห้องนอน", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image61.jpg" },
  { title: "บ้านพักอาศัย ชุมพร — ห้องน้ำ", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image62.jpg" },
  { title: "บ้านพักอาศัย ชุมพร — ห้องนอนใหญ่", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image63.jpg" },
  { title: "Reignwood Park — ห้องครัว", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image1.jpg" },
  { title: "Reignwood Park — ห้องนั่งเล่น", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image6.jpg" },
  { title: "Reignwood Park — ห้องนั่งเล่นและทานอาหาร", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image7.jpg" },
  { title: "Reignwood Park — ตู้ครัว Built-in", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image8.jpg" },
  { title: "Reignwood Park — ครัวและมุมทานอาหาร", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image9.jpg" },
  { title: "Reignwood Park — เคาน์เตอร์ครัว", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image10.jpg" },
  { title: "Reignwood Park — มุมดูทีวี", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image11.jpg" },
  { title: "Reignwood Park — ห้องนอน", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image12.jpg" },
  { title: "Reignwood Park — ห้องน้ำ", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image13.jpg" },
  { title: "Reignwood Park — ห้องนอนใหญ่", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image14.jpg" },
  { title: "Reignwood Park — ห้องนอนแขก", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image15.jpg" },
  { title: "Reignwood Park — ห้องนอนเด็ก", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image16.jpg" },
  { title: "Reignwood Park — ห้องเล่นเด็ก", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image17.jpg" },
  { title: "Reignwood Park — ห้องทำงาน", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image24.jpg" },
  { title: "Reignwood Park — ห้องรับแขก", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image25.jpg" },
  { title: "Reignwood Park — ห้องครัวโทนเขียว", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image26.jpg" },
  { title: "Reignwood Park — ห้องนั่งเล่นโทนน้ำเงิน", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image27.jpg" },
  { title: "Reignwood Park — ห้องนอนโทนน้ำเงิน", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image28.jpg" },
  { title: "Reignwood Park — ห้องนอนโทนเขียว", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image29.jpg" },
  { title: "Reignwood Park — ห้องนอนโทนเหลือง", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image30.jpg" },
  { title: "Maiyalap 14 — ห้องรับแขก", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image102.jpg" },
  { title: "Maiyalap 14 — มุมนั่งเล่น", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image106.jpg" },
  { title: "Maiyalap 14 — โถงเปียโน", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image107.jpg" },
  { title: "Maiyalap 14 — ห้องนั่งเล่นและเปียโน", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image109.jpg" },
  { title: "Maiyalap 14 — ห้องนั่งเล่นใหญ่", category: "ที่พักอาศัย", type: "ภาพออกแบบ 3D", image: "images/image110.jpg" },
  { title: "โรงเรียนอนุบาล — ห้องเรียนรวม", category: "โรงเรียนอนุบาล", type: "ภาพออกแบบ 3D", image: "images/image71.jpg" },
  { title: "โรงเรียนอนุบาล — มุมกิจกรรม", category: "โรงเรียนอนุบาล", type: "ภาพออกแบบ 3D", image: "images/image72.jpg" },
  { title: "โรงเรียนอนุบาล — ห้องนอนกลางวัน", category: "โรงเรียนอนุบาล", type: "ภาพออกแบบ 3D", image: "images/image73.jpg" },
  { title: "โรงเรียนอนุบาล — ห้องพักผ่อน", category: "โรงเรียนอนุบาล", type: "ภาพออกแบบ 3D", image: "images/image74.jpg" },
  { title: "โรงเรียนอนุบาล — ห้องกิจกรรมและเวที", category: "โรงเรียนอนุบาล", type: "ภาพออกแบบ 3D", image: "images/image76.jpg" },
  { title: "โรงเรียนอนุบาล — โถงกิจกรรม", category: "โรงเรียนอนุบาล", type: "ภาพออกแบบ 3D", image: "images/image79.jpg" },
  { title: "โรงเรียนอนุบาล — มุมทานอาหาร", category: "โรงเรียนอนุบาล", type: "ภาพออกแบบ 3D", image: "images/image80.jpg" },
  { title: "โรงเรียนอนุบาล — ห้องเรียน", category: "โรงเรียนอนุบาล", type: "ภาพออกแบบ 3D", image: "images/image81.jpg" },
  { title: "โรงเรียนอนุบาล — ห้องครัวเด็ก", category: "โรงเรียนอนุบาล", type: "ภาพออกแบบ 3D", image: "images/image82.jpg" },
  { title: "โรงเรียนอนุบาล — ห้องทำอาหาร", category: "โรงเรียนอนุบาล", type: "ภาพออกแบบ 3D", image: "images/image83.jpg" },
  { title: "โรงเรียนอนุบาล — ห้องเรียนศิลปะ", category: "โรงเรียนอนุบาล", type: "ภาพออกแบบ 3D", image: "images/image84.jpg" },
  { title: "โรงเรียนอนุบาล — ห้องปฏิบัติการ", category: "โรงเรียนอนุบาล", type: "ภาพออกแบบ 3D", image: "images/image85.jpg" },
  { title: "ศูนย์การเรียนรู้ — ห้องเรียน", category: "พื้นที่การเรียนรู้", type: "ภาพออกแบบ 3D", image: "images/image86.jpg" },
  { title: "ศูนย์การเรียนรู้ — ห้องบรรยาย", category: "พื้นที่การเรียนรู้", type: "ภาพออกแบบ 3D", image: "images/image87.jpg" },
  { title: "ศูนย์การเรียนรู้ — ห้องประชุม", category: "พื้นที่การเรียนรู้", type: "ภาพออกแบบ 3D", image: "images/image88.jpg" },
  { title: "ศูนย์การเรียนรู้ — ห้องปฏิบัติการ", category: "พื้นที่การเรียนรู้", type: "ภาพออกแบบ 3D", image: "images/image89.jpg" },
  { title: "ศูนย์การเรียนรู้ — ห้องเรียนรวม", category: "พื้นที่การเรียนรู้", type: "ภาพออกแบบ 3D", image: "images/image90.jpg" },
  { title: "ศูนย์การเรียนรู้ — ห้องกิจกรรม", category: "พื้นที่การเรียนรู้", type: "ภาพออกแบบ 3D", image: "images/image91.jpg" },
  { title: "ศูนย์การเรียนรู้ — มุมอ่านหนังสือ", category: "พื้นที่การเรียนรู้", type: "ภาพออกแบบ 3D", image: "images/image93.jpg" },
  { title: "ศูนย์การเรียนรู้ — ทางเดิน", category: "พื้นที่การเรียนรู้", type: "ภาพออกแบบ 3D", image: "images/image94.jpg" },
  { title: "ศูนย์การเรียนรู้ — ลานนั่งอ่าน", category: "พื้นที่การเรียนรู้", type: "ภาพออกแบบ 3D", image: "images/image95.jpg" },
  { title: "ศูนย์การเรียนรู้ — มุมพักผ่อน", category: "พื้นที่การเรียนรู้", type: "ภาพออกแบบ 3D", image: "images/image96.jpg" },
  { title: "ศูนย์การเรียนรู้ — ห้องสมุดเพดานโค้ง", category: "พื้นที่การเรียนรู้", type: "ภาพออกแบบ 3D", image: "images/image97.jpg" },
  { title: "ศูนย์การเรียนรู้ — โซนนั่งเล่น", category: "พื้นที่การเรียนรู้", type: "ภาพออกแบบ 3D", image: "images/image98.jpg" },
  { title: "ศูนย์การเรียนรู้ — ลานขั้นบันได", category: "พื้นที่การเรียนรู้", type: "ภาพออกแบบ 3D", image: "images/image99.jpg" },
  { title: "ศูนย์การเรียนรู้ — มุมทำงาน", category: "พื้นที่การเรียนรู้", type: "ภาพออกแบบ 3D", image: "images/image100.jpg" },
  { title: "ศูนย์การเรียนรู้ — ห้องอ่านหนังสือ", category: "พื้นที่การเรียนรู้", type: "ภาพออกแบบ 3D", image: "images/image101.jpg" },
  { title: "อาคารเรียน — ทางเข้า", category: "ภายนอกอาคาร", type: "ภาพออกแบบ 3D", image: "images/image111.jpg" },
  { title: "อาคารเรียน — ทางเดินในสวน", category: "ภายนอกอาคาร", type: "ภาพออกแบบ 3D", image: "images/image113.jpg" },
];
