// ============================================================
//  ข้อมูลเว็บไซต์ — แก้ไขที่ไฟล์นี้ที่เดียว
// ============================================================

const CONTACT = {
  phone: { tel: "0989835090", display: "098-983-5090" },
  // ขึ้นบรรทัดใหม่ด้วย \n
  address: "9/69 Moo 1, Soi Ban Klang 1/4 (Soi Liap Khlong Prapa)\nPathum–Rangsit Road, Ban Klang Subdistrict\nMueang Pathum Thani District\nPathum Thani 12000, Thailand",
};
// LINE: ใช้รูป QR Code ที่ images/line-qr.jpg (เปลี่ยนรูปนี้ถ้ามี QR ใหม่)

// ผลงาน: 1 project = ภาพปก 1 ภาพ + ภาพทั้งหมดของโครงการ (ไฟล์อยู่ใน images/)
// slug ใช้เป็นลิงก์ของหน้าโครงการ เช่น #project/chumphon-house (ใช้ a-z, 0-9 และ - เท่านั้น)
// ภาพแรกใน images คือภาพแรกที่เห็นในหน้าโครงการ
const PROJECTS = [
  {
    slug: "reignwood-park",
    title: "Reignwood Park",
    category: "Residential",
    location: "Thailand",
    cover: "images/image23.jpg",
    description: "A family residence in two moods — light, natural-toned rooms on one side and deep navy and forest-green classics on the other.",
    images: [
      { src: "images/image23.jpg", caption: "Living room" },
      { src: "images/image18.jpg", caption: "Kitchen" },
      { src: "images/image1.jpg", caption: "Kitchen" },
      { src: "images/image6.jpg", caption: "Living room" },
      { src: "images/image7.jpg", caption: "Living & dining" },
      { src: "images/image8.jpg", caption: "Built-in kitchen cabinets" },
      { src: "images/image9.jpg", caption: "Kitchen & dining" },
      { src: "images/image10.jpg", caption: "Kitchen island" },
      { src: "images/image11.jpg", caption: "TV lounge" },
      { src: "images/image12.jpg", caption: "Bedroom" },
      { src: "images/image13.jpg", caption: "Bathroom" },
      { src: "images/image14.jpg", caption: "Master bedroom" },
      { src: "images/image15.jpg", caption: "Guest bedroom" },
      { src: "images/image16.jpg", caption: "Kid's bedroom" },
      { src: "images/image17.jpg", caption: "Playroom" },
      { src: "images/image24.jpg", caption: "Study" },
      { src: "images/image25.jpg", caption: "Lounge" },
      { src: "images/image26.jpg", caption: "Green kitchen" },
      { src: "images/image27.jpg", caption: "Navy living room" },
      { src: "images/image28.jpg", caption: "Navy bedroom" },
      { src: "images/image29.jpg", caption: "Green bedroom" },
      { src: "images/image30.jpg", caption: "Yellow bedroom" },
    ],
  },
  {
    slug: "chumphon-house",
    title: "Chumphon House",
    category: "Residential",
    location: "Chumphon",
    cover: "images/image58.jpg",
    description: "A tropical modern home with double-height living spaces, warm natural materials and wide openings to the garden.",
    images: [
      { src: "images/image58.jpg", caption: "Living room" },
      { src: "images/image55.jpg", caption: "Stair hall" },
      { src: "images/image57.jpg", caption: "Double-height hall" },
      { src: "images/image56.jpg", caption: "Dining room" },
      { src: "images/image60.jpg", caption: "Kitchen" },
      { src: "images/image59.jpg", caption: "Study" },
      { src: "images/image61.jpg", caption: "Bedroom" },
      { src: "images/image63.jpg", caption: "Master bedroom" },
      { src: "images/image62.jpg", caption: "Bathroom" },
    ],
  },
  {
    slug: "maiyalap-14",
    title: "Maiyalap 14",
    category: "Residential",
    location: "Bangkok",
    cover: "images/image108.jpg",
    description: "A classic residence with sculptural lighting, herringbone floors and a grand piano hall.",
    images: [
      { src: "images/image108.jpg", caption: "Living room" },
      { src: "images/image102.jpg", caption: "Reception room" },
      { src: "images/image106.jpg", caption: "Sitting area" },
      { src: "images/image107.jpg", caption: "Piano hall" },
      { src: "images/image109.jpg", caption: "Living room & piano" },
      { src: "images/image110.jpg", caption: "Main living room" },
    ],
  },
  {
    slug: "kindergarten",
    title: "Kindergarten",
    category: "Education",
    location: "Thailand",
    cover: "images/image64.jpg",
    description: "Playful learning spaces with cloud ceilings, soft curves and child-scaled furniture.",
    images: [
      { src: "images/image64.jpg", caption: "Classroom" },
      { src: "images/image75.jpg", caption: "Indoor playground" },
      { src: "images/image71.jpg", caption: "Open classroom" },
      { src: "images/image72.jpg", caption: "Activity corner" },
      { src: "images/image73.jpg", caption: "Nap room" },
      { src: "images/image74.jpg", caption: "Rest room" },
      { src: "images/image76.jpg", caption: "Activity hall & stage" },
      { src: "images/image79.jpg", caption: "Activity hall" },
      { src: "images/image80.jpg", caption: "Dining area" },
      { src: "images/image81.jpg", caption: "Classroom" },
      { src: "images/image82.jpg", caption: "Kids' kitchen" },
      { src: "images/image83.jpg", caption: "Cooking room" },
      { src: "images/image84.jpg", caption: "Art room" },
      { src: "images/image85.jpg", caption: "Workshop" },
    ],
  },
  {
    slug: "learning-center",
    title: "Learning Center",
    category: "Education",
    location: "Thailand",
    cover: "images/image92.jpg",
    description: "A library and learning center with stepped reading terraces, lounges and flexible classrooms.",
    images: [
      { src: "images/image92.jpg", caption: "Library" },
      { src: "images/image97.jpg", caption: "Library hall" },
      { src: "images/image86.jpg", caption: "Classroom" },
      { src: "images/image87.jpg", caption: "Lecture room" },
      { src: "images/image88.jpg", caption: "Meeting room" },
      { src: "images/image89.jpg", caption: "Lab" },
      { src: "images/image90.jpg", caption: "Classroom" },
      { src: "images/image91.jpg", caption: "Activity room" },
      { src: "images/image93.jpg", caption: "Reading area" },
      { src: "images/image94.jpg", caption: "Corridor" },
      { src: "images/image95.jpg", caption: "Reading terrace" },
      { src: "images/image96.jpg", caption: "Lounge" },
      { src: "images/image98.jpg", caption: "Lounge zone" },
      { src: "images/image99.jpg", caption: "Stepped seating" },
      { src: "images/image100.jpg", caption: "Work corner" },
      { src: "images/image101.jpg", caption: "Reading room" },
    ],
  },
  {
    slug: "maya-rob-house",
    title: "Maya Rob House",
    category: "Residential",
    location: "Thailand",
    cover: "images/image113.jpg",
    description: "Building exterior and landscape — timber screens, a moon gate and a stepping-stone garden path.",
    images: [
      { src: "images/image112.jpg", caption: "Exterior" },
      { src: "images/image111.jpg", caption: "Entrance" },
      { src: "images/image113.jpg", caption: "Garden path" },
    ],
  },
];
