// รายการผลงาน — แก้ไข/เพิ่มที่นี่ที่เดียว
// image: ใส่ path รูปของคุณ เช่น "images/brand-01.jpg" (วางไฟล์ไว้ในโฟลเดอร์ images/)
// category: หมวดหมู่จะถูกสร้างเป็นปุ่มกรองให้อัตโนมัติ
const PROJECTS = [
  { title: "Kinfolk Café", category: "Branding", year: 2026,
    image: "https://picsum.photos/seed/kinfolk/900/1200",
    description: "อัตลักษณ์แบรนด์สำหรับคาเฟ่ย่านอารีย์ โลโก้ แพ็กเกจ และป้ายร้าน" },
  { title: "Monsoon Festival", category: "Poster", year: 2026,
    image: "https://picsum.photos/seed/monsoon/900/600",
    description: "โปสเตอร์ชุดสำหรับเทศกาลดนตรีฤดูฝน" },
  { title: "Finly App", category: "UI", year: 2025,
    image: "https://picsum.photos/seed/finly/900/700",
    description: "ออกแบบแอปจัดการการเงินส่วนบุคคล" },
  { title: "Old Town Light", category: "Photography", year: 2025,
    image: "https://picsum.photos/seed/oldtown/900/1300",
    description: "ภาพถ่ายแสงยามเช้าในย่านเมืองเก่า" },
  { title: "Saeng Tea", category: "Branding", year: 2025,
    image: "https://picsum.photos/seed/saengtea/900/900",
    description: "บรรจุภัณฑ์ชาออร์แกนิกจากเชียงราย" },
  { title: "Type & Space", category: "Poster", year: 2025,
    image: "https://picsum.photos/seed/typespace/900/1250",
    description: "งานทดลองตัวอักษรไทยบนพื้นที่ว่าง" },
  { title: "Wander Travel", category: "UI", year: 2024,
    image: "https://picsum.photos/seed/wander/900/650",
    description: "เว็บไซต์จองทริปท่องเที่ยวชุมชน" },
  { title: "Coastline", category: "Photography", year: 2024,
    image: "https://picsum.photos/seed/coastline/900/600",
    description: "ชุดภาพทะเลฝั่งอันดามัน" },
  { title: "Baan Studio", category: "Branding", year: 2024,
    image: "https://picsum.photos/seed/baanstudio/900/1100",
    description: "อัตลักษณ์สตูดิโอสถาปัตยกรรม" },
  { title: "Night Market", category: "Photography", year: 2024,
    image: "https://picsum.photos/seed/nightmarket/900/1200",
    description: "สีสันตลาดกลางคืน" },
  { title: "Bloom Exhibition", category: "Poster", year: 2023,
    image: "https://picsum.photos/seed/bloom/900/800",
    description: "โปสเตอร์นิทรรศการศิลปะดอกไม้" },
  { title: "Pulse Dashboard", category: "UI", year: 2023,
    image: "https://picsum.photos/seed/pulse/900/1000",
    description: "แดชบอร์ดวิเคราะห์ข้อมูลสุขภาพ" },
];
